SUMMARY = "PROJECTNAME image with flatpak 3rd-party application support."
DESCRIPTION = "PROJECTNAME image with flatpak 3rd-party application support."

REFKIT_IMAGE_NOSWUPD_EXTRA_FEATURES ?= "${REFKIT_IMAGE_FEATURES_REFERENCE}"
REFKIT_IMAGE_NOSWUPD_EXTRA_INSTALL ?= "${REFKIT_IMAGE_INSTALL_REFERENCE}"
REFKIT_IMAGE_EXTRA_FEATURES += "${REFKIT_IMAGE_NOSWUPD_EXTRA_FEATURES}"
REFKIT_IMAGE_EXTRA_INSTALL += "${REFKIT_IMAGE_NOSWUPD_EXTRA_INSTALL}"

REFKIT_IMAGE_EXTRA_FEATURES_append = " tools-sdk dev-pkgs"
REFKIT_IMAGE_EXTRA_INSTALL_append = " git subversion"

inherit refkit-image
